const express = require('express');
const PDFDocument = require('pdfkit');
const pool = require('../db/pool');
const { auth } = require('../middleware/auth');

const router = express.Router();
router.use(auth);
const money = (n) => 'PKR ' + Number(n || 0).toLocaleString();

// Report card PDF
router.get('/report-card/:studentId', async (req, res) => {
  const s = req.user.school_id;
  const stu = (await pool.query(
    `SELECT st.*, c.name class_name FROM students st LEFT JOIN classes c ON c.id=st.class_id WHERE st.id=$1 AND st.school_id=$2`,
    [req.params.studentId, s])).rows[0];
  if (!stu) return res.status(404).json({ error: 'Student not found' });
  const school = (await pool.query(`SELECT name, primary_color FROM schools WHERE id=$1`, [s])).rows[0];
  const grades = (await pool.query(
    `SELECT su.name subject, g.assignment_name, g.obtained_marks, g.total_marks,
       ROUND(g.obtained_marks/NULLIF(g.total_marks,0)*100,1) pct
     FROM grades g LEFT JOIN subjects su ON su.id=g.subject_id WHERE g.student_id=$1 ORDER BY su.name`, [req.params.studentId])).rows;
  const att = (await pool.query(`SELECT status, count(*)::int c FROM student_attendance WHERE student_id=$1 GROUP BY status`, [req.params.studentId])).rows;
  const present = att.find((a) => a.status === 'Present')?.c || 0;
  const totalAtt = att.reduce((x, a) => x + a.c, 0) || 1;
  const avg = grades.length ? (grades.reduce((x, g) => x + Number(g.pct || 0), 0) / grades.length).toFixed(1) : '0';

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="report-card-${stu.roll_no || stu.id}.pdf"`);
  doc.pipe(res);
  const accent = school.primary_color || '#4F46E5';

  doc.rect(0, 0, doc.page.width, 90).fill(accent);
  doc.fillColor('#fff').fontSize(22).text(school.name, 50, 30);
  doc.fontSize(12).fillColor('#e5e7eb').text('Student Report Card', 50, 60);
  doc.fillColor('#111').moveDown(4);

  doc.fontSize(11).fillColor('#374151');
  const y0 = 120;
  doc.text(`Name: ${stu.first_name} ${stu.last_name}`, 50, y0);
  doc.text(`Roll No: ${stu.roll_no || '—'}`, 320, y0);
  doc.text(`Class: ${stu.class_name || '—'}`, 50, y0 + 18);
  doc.text(`Gender: ${stu.gender || '—'}`, 320, y0 + 18);

  doc.moveTo(50, y0 + 48).lineTo(545, y0 + 48).strokeColor('#e5e7eb').stroke();

  // grades table
  let y = y0 + 65;
  doc.fontSize(13).fillColor(accent).text('Academic Performance', 50, y); y += 22;
  doc.fontSize(10).fillColor('#6b7280');
  doc.text('Subject', 50, y); doc.text('Assessment', 200, y); doc.text('Marks', 380, y); doc.text('%', 480, y);
  y += 6; doc.moveTo(50, y + 8).lineTo(545, y + 8).strokeColor('#e5e7eb').stroke(); y += 16;
  doc.fillColor('#111827').fontSize(10);
  grades.forEach((g) => {
    doc.text(g.subject || '—', 50, y, { width: 145 });
    doc.text(g.assignment_name, 200, y, { width: 170 });
    doc.text(`${g.obtained_marks}/${g.total_marks}`, 380, y);
    doc.text(`${g.pct}%`, 480, y);
    y += 18;
  });

  y += 15;
  doc.moveTo(50, y).lineTo(545, y).strokeColor('#e5e7eb').stroke(); y += 15;
  doc.fontSize(11).fillColor('#374151');
  doc.text(`Overall Average: ${avg}%`, 50, y);
  doc.text(`Attendance: ${Math.round((present / totalAtt) * 100)}%  (${present}/${totalAtt} present)`, 320, y);

  doc.fontSize(9).fillColor('#9ca3af').text('Generated by Acadex · ' + new Date().toLocaleDateString(), 50, 760, { align: 'center', width: 495 });
  doc.end();
});

// Fee voucher/receipt PDF
router.get('/fee-voucher/:feeId', async (req, res) => {
  const s = req.user.school_id;
  const f = (await pool.query(
    `SELECT f.*, st.first_name||' '||st.last_name student, st.roll_no, c.name class_name
     FROM tuition_fee f JOIN students st ON st.id=f.student_id LEFT JOIN classes c ON c.id=st.class_id
     WHERE f.id=$1 AND f.school_id=$2`, [req.params.feeId, s])).rows[0];
  if (!f) return res.status(404).json({ error: 'Fee record not found' });
  const school = (await pool.query(`SELECT name, primary_color FROM schools WHERE id=$1`, [s])).rows[0];
  const accent = school.primary_color || '#4F46E5';

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `inline; filename="fee-voucher-${f.receipt_id}.pdf"`);
  doc.pipe(res);

  doc.rect(0, 0, doc.page.width, 90).fill(accent);
  doc.fillColor('#fff').fontSize(22).text(school.name, 50, 30);
  doc.fontSize(12).fillColor('#e5e7eb').text('Fee Voucher / Receipt', 50, 60);

  doc.fillColor('#374151').fontSize(11);
  let y = 120;
  doc.text(`Receipt #: ${f.receipt_id}`, 50, y); doc.text(`Date: ${new Date(f.payment_date).toLocaleDateString()}`, 350, y); y += 20;
  doc.text(`Student: ${f.student}`, 50, y); doc.text(`Roll No: ${f.roll_no || '—'}`, 350, y); y += 20;
  doc.text(`Class: ${f.class_name || '—'}`, 50, y); y += 30;

  doc.moveTo(50, y).lineTo(545, y).strokeColor('#e5e7eb').stroke(); y += 20;
  const row = (label, val, bold) => { doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(12).fillColor('#111827'); doc.text(label, 60, y); doc.text(val, 400, y); y += 26; };
  row('Total Fee', money(f.total_fee));
  row('Paid Amount', money(f.paid_amount));
  row('Remaining Balance', money(f.remaining_balance));
  doc.moveTo(50, y).lineTo(545, y).strokeColor('#e5e7eb').stroke(); y += 16;
  row('Status', f.payment_status, true);

  doc.font('Helvetica').fontSize(9).fillColor('#9ca3af').text('This is a computer-generated voucher from Acadex.', 50, 760, { align: 'center', width: 495 });
  doc.end();
});

module.exports = router;
